apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    metadata:
      {{- with .Values.jobAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ddns-updater.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              env:
                - name: DDNS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ddns-updater.fullname" . }}
                      key: password
                - name: IP_QUERY_URL
                  value: {{ .Values.queryIpUrl }}
                - name: DDNS_API_URL
                  value: {{ .Values.updateApiUrl }}
                - name: DDNS_HOSTNAME
                  value: {{ .Values.hostname }}
                - name: DDNS_USERNAME
                  value: {{ .Values.username }}
                - name: DDNS_USER_AGENT
                  value: {{ .Values.userAgent | quote }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
